version: '2'
services:
  mysql:
    image: mysql:5.6
    # Debug access:
    #ports:
    #  - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    # Reduce memory usage with the minimum table definition cache:
    command: "mysqld --table-definition-cache=400"
  phpbb:
    #image: blueimp/phpbb:3.1
    image: bbtest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DBPASSWD
    hostname: $SERVER_NAME
    #volumes:
    #  - "./ssl:/etc/apache2/ssl"
  #backup:
  #  image: blueimp/phpbb-s3-backup
  #  environment:
  #    - DBPASSWD
  #    - S3_BUCKET
  #    - AWS_ACCESS_KEY_ID
  #    - AWS_SECRET_ACCESS_KEY
  #  volumes_from:
  #    - phpbb
